# Generated by Django 5.2.5 on 2025-08-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_autresinfrastructures_bacs_batimentsadministratifs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piste',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
