# Generated by Django 5.2.5 on 2025-08-28 13:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_piste_options_alter_login_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='piste',
            name='communes_rurales_id',
            field=models.ForeignKey(blank=True, db_column='communes_rurales_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.communerurale'),
        ),
        migrations.AddField(
            model_name='piste',
            name='login_id',
            field=models.ForeignKey(blank=True, db_column='login_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.login'),
        ),
        migrations.AlterField(
            model_name='piste',
            name='code_piste',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='frequence_trafic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=32628),
        ),
        migrations.AlterField(
            model_name='piste',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Chaussees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=32628)),
                ('code_piste', models.CharField(max_length=254)),
                ('code_gps', models.CharField(max_length=254)),
                ('endroit', models.CharField(max_length=254)),
                ('type_chaussee', models.CharField(blank=True, max_length=254, null=True)),
                ('etat_piste', models.CharField(blank=True, max_length=254, null=True)),
                ('x_debut_chaussee', models.FloatField()),
                ('y_debut_chaussee', models.FloatField()),
                ('x_fin_chaussee', models.FloatField()),
                ('y_fin_chaussee', models.FloatField()),
                ('points_json', models.TextField()),
                ('distance_totale_m', models.FloatField()),
                ('nombre_points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('login_id', models.ForeignKey(blank=True, db_column='login_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.login')),
            ],
            options={
                'db_table': 'chaussees',
                'managed': True,
            },
        ),
    ]
