# Generated by Django 5.2.5 on 2025-08-28 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_piste_communes_rurales_id_piste_login_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chaussees',
        ),
    ]
