# Generated by Django 6.0.1 on 2026-02-01 01:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_piste_created_at_alter_piste_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaussees',
            fields=[
                ('fid', models.BigAutoField(db_column='fid', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('sqlite_id', models.BigIntegerField(blank=True, db_column='id', null=True)),
                ('x_debut_ch', models.FloatField(blank=True, null=True)),
                ('y_debut_ch', models.FloatField(blank=True, null=True)),
                ('x_fin_ch', models.FloatField(blank=True, null=True)),
                ('y_fin_chau', models.FloatField(blank=True, null=True)),
                ('type_chaus', models.CharField(blank=True, max_length=254, null=True)),
                ('etat_piste', models.CharField(blank=True, max_length=254, null=True)),
                ('endroit', models.CharField(blank=True, max_length=32, null=True)),
                ('code_gps', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'chaussees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnquetePolygone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('superficie_en_ha', models.FloatField(blank=True, null=True)),
                ('communes_rurales_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enquete_polygone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointsCoupures',
            fields=[
                ('fid', models.BigAutoField(db_column='fid', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('sqlite_id', models.BigIntegerField(blank=True, db_column='id', null=True)),
                ('cause_coup', models.CharField(blank=True, max_length=50, null=True)),
                ('x_point_co', models.FloatField(blank=True, null=True)),
                ('y_point_co', models.FloatField(blank=True, null=True)),
                ('code_gps', models.CharField(blank=True, max_length=254, null=True)),
                ('chaussee_id', models.BigIntegerField(blank=True, db_column='chaussee_id', null=True)),
                ('created_at', models.CharField(blank=True, max_length=24, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'points_coupures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointsCritiques',
            fields=[
                ('fid', models.BigAutoField(db_column='fid', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('sqlite_id', models.BigIntegerField(blank=True, db_column='id', null=True)),
                ('type_point', models.CharField(blank=True, max_length=50, null=True)),
                ('x_point_cr', models.FloatField(blank=True, null=True)),
                ('y_point_cr', models.FloatField(blank=True, null=True)),
                ('code_gps', models.CharField(blank=True, max_length=254, null=True)),
                ('chaussee_id', models.BigIntegerField(blank=True, db_column='chaussee_id', null=True)),
                ('created_at', models.CharField(blank=True, max_length=24, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'points_critiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('fid', models.BigAutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('sqlite_id', models.IntegerField(blank=True, db_column='id', null=True)),
                ('x_site', models.FloatField(blank=True, null=True)),
                ('y_site', models.FloatField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_gps', models.CharField(blank=True, max_length=254, null=True)),
                ('code_piste', models.CharField(blank=True, max_length=50, null=True)),
                ('login_id', models.IntegerField(blank=True, null=True)),
                ('commune_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=24, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'sites',
                'managed': True,
            },
        ),
    ]
