# Generated by Django 6.0.1 on 2026-02-01 01:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chaussees_enquetepolygone_pointscoupures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PprItial',
            fields=[
                ('fid', models.BigAutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('projet', models.CharField(blank=True, max_length=254, null=True)),
                ('travaux_debut', models.CharField(blank=True, max_length=254, null=True)),
                ('travaux_fin', models.IntegerField(blank=True, null=True)),
                ('type_de_realisation', models.CharField(blank=True, max_length=254, null=True)),
                ('superficie_enquetes_ha', models.FloatField(blank=True, null=True)),
                ('commune_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ppr_itial',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
