# Generated by Django 6.0.1 on 2026-02-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ppritial_delete_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='piste',
            name='debut_travaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='fin_travaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='financement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='plateforme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='projet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='relief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='vegetation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
