# Generated by Django 6.0.1 on 2026-02-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_piste_debut_travaux_piste_fin_travaux_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterfacePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(choices=[('carte_globale', 'Carte Globale'), ('gestion_donnees', 'Gestion Données'), ('tableau_bord', 'Tableau de Bord'), ('gestion_utilisateurs', 'Gestion Utilisateurs'), ('suivi_donnees', 'Suivi Données'), ('export_carte', 'Export Carte')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_interface_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_permission_audit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_prefectures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_regions',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='piste',
            name='cout_investissement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='fonctionnalite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='interet_socio_administratif',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='niveau_service',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='note_globale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='population_desservie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='potentiel_agricole',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='protection_environnement',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
